# Generated by Django 3.2.3 on 2021-09-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_id', models.IntegerField()),
                ('token_hex', models.CharField(max_length=16)),
            ],
        ),
    ]
